# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_repass.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form_repass(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(511, 234)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 10, 111, 21))
        self.label.setStyleSheet("font: italic 14pt \"Arial\";")
        self.label.setObjectName("label")
        self.pushButton_put = QtWidgets.QPushButton(Form)
        self.pushButton_put.setGeometry(QtCore.QRect(190, 180, 93, 28))
        self.pushButton_put.setObjectName("pushButton_put")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(90, 50, 291, 111))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_user = QtWidgets.QLabel(self.widget)
        self.label_user.setStyleSheet("font: 10pt \"Arial\";")
        self.label_user.setObjectName("label_user")
        self.gridLayout.addWidget(self.label_user, 0, 0, 1, 1)
        self.lineEdit_user = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_user.setEnabled(True)
        self.lineEdit_user.setFrame(True)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.gridLayout.addWidget(self.lineEdit_user, 0, 1, 1, 1)
        self.label_pass = QtWidgets.QLabel(self.widget)
        self.label_pass.setStyleSheet("font: 10pt \"Arial\";")
        self.label_pass.setObjectName("label_pass")
        self.gridLayout.addWidget(self.label_pass, 1, 0, 1, 1)
        self.lineEdit_pass = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.gridLayout.addWidget(self.lineEdit_pass, 1, 1, 1, 1)
        self.label_repass = QtWidgets.QLabel(self.widget)
        self.label_repass.setStyleSheet("font: 10pt \"Arial\";")
        self.label_repass.setObjectName("label_repass")
        self.gridLayout.addWidget(self.label_repass, 2, 0, 1, 1)
        self.lineEdit_repass = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_repass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_repass.setObjectName("lineEdit_repass")
        self.gridLayout.addWidget(self.lineEdit_repass, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "修改密码"))
        self.pushButton_put.setText(_translate("Form", "提交"))
        self.label_user.setText(_translate("Form", "用户名"))
        self.label_pass.setText(_translate("Form", "新密码"))
        self.label_repass.setText(_translate("Form", "重复确认"))
